### ISSUE TITLE
Launch Configuration shows between media controls & song title 

### ISSUE THREAD

**Issue by randrade23** [ShyykoSerhiy/vscode-spotify#89] opened 2019-02-19 21:23 UTC
![image](https://user-images.githubusercontent.com/2223723/53048380-81d81a80-348c-11e9-820c-e612ee436800.png)

This is probably caused by a not low enough priority for the Spotify controls in the status bar. This is a node.js project, if it makes any difference...

**Comment by ShyykoSerhiy** [comment] 2019-02-19 21:25
Please have a look at https://github.com/ShyykoSerhiy/vscode-spotify/issues/33#issuecomment-375766550. 
Duplicate of #33 .

**Closed by ShyykoSerhiy** 2019-02-19 21:25 UTC
